### ISSUE TITLE
Assuming asprintf is just available everywhere is unwarranted.

### ISSUE THREAD

**Issue by HBBroeker** [tefletch/gscope#1]
asprintf() is a GNU extension.  You should not blindly assume it to be present.

**Comment by HBBroeker** [comment]
At the very least, the corresponding feature macros have to be auto-checked for, and config.h has to be actully pulled in early enough in the source to get them to work on the system headers.

(see pull  request  #3 )

**Comment by tefletch** [comment]
I've actually avoided using asprintf() for years.  Seemed like it has permeated almost everywhere and was fairly universally available at this point, so I committed to transitioning to using it.   I'll take a look at merging you suggestions.   Thanks for the contribution.

**Comment by tefletch** [comment]
Suggested fix(es) have been merged

**Comment by HBBroeker** [comment]
The fix you did didn't actually fix the issue at all ;-{  Now you're using vasprintf(), which is every bit as unavailable on non-GNU platforms as asprintf(), and you **still** forgot to actually include "config.h" in time for it to have an effect...

**Comment by tefletch** [comment]
I've pushed the "config.h" cleanup.  I also intentionally kept using the
asprintf() family of functions.

The new  my_asprintf()  wrapper provides a hook where non-GNU platform
developers could create their own equivalent function [if needed].

Out of curiosity, what platform are you attempting to build gscope on?  Are
you captive to a non-GNU policy?  I was thinking non-GNU enabled/capable
platforms for software development are fairly rare at this point in time.
Maybe I'm leading more of a "sheltered life" than I thought :-)

Tom

**Comment by HBBroeker** [comment]
There's one small flaw in my changes to autogen.sh that can cause config.h to lack the necessary macros to enable GNU extensions, even on platforms that have them.  It has to check for AC_CONFIG_HEADER instead of AM_CONFIG_HEADER, now, otherwise it'll forget to run autoheader.

And please don't 
`#include <config.h>`
because that is not a system header.  It should really be
`#include "config.h"`

> Out of curiosity, what platform are you attempting to build gscope on? 

That's actually beside the point.  It's Cygwin and, like quite a number of other platforms, it will not always expose non-standard features unless they're explicitly enabled.  Even the Linux manpages tell you to define _GNU_SOURCE first to get them.

> Maybe I'm leading more of a "sheltered life" than I thought :-) 

Quite possibly.  People used to have to be reminded that not all the world's a VAX.  Nowadays, this may have to become "not all the world's Linux".

**Comment by tefletch** [comment]
I've added some changes that will hopefully help platforms without
asprintf() and friends.  Check out the tip of the "master" branch.
